# Importing Necessary Libraries

In [2]:
import pandas as pd
import numpy as np
import matplotlib as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

# Loading The Data

In [3]:
df = pd.read_csv("C:/Users/DataScience/Projects using Jupyter/Credit Card Fraud Detection/Dataset/creditcard.csv")

In [4]:
df

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
284802,172786.0,-11.881118,10.071785,-9.834783,-2.066656,-5.364473,-2.606837,-4.918215,7.305334,1.914428,...,0.213454,0.111864,1.014480,-0.509348,1.436807,0.250034,0.943651,0.823731,0.77,0
284803,172787.0,-0.732789,-0.055080,2.035030,-0.738589,0.868229,1.058415,0.024330,0.294869,0.584800,...,0.214205,0.924384,0.012463,-1.016226,-0.606624,-0.395255,0.068472,-0.053527,24.79,0
284804,172788.0,1.919565,-0.301254,-3.249640,-0.557828,2.630515,3.031260,-0.296827,0.708417,0.432454,...,0.232045,0.578229,-0.037501,0.640134,0.265745,-0.087371,0.004455,-0.026561,67.88,0
284805,172788.0,-0.240440,0.530483,0.702510,0.689799,-0.377961,0.623708,-0.686180,0.679145,0.392087,...,0.265245,0.800049,-0.163298,0.123205,-0.569159,0.546668,0.108821,0.104533,10.00,0
284806,172792.0,-0.533413,-0.189733,0.703337,-0.506271,-0.012546,-0.649617,1.577006,-0.414650,0.486180,...,0.261057,0.643078,0.376777,0.008797,-0.473649,-0.818267,-0.002415,0.013649,217.00,0

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 284807 entries, 0 to 284806
Data columns (total 31 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   Time    284807 non-null  float64
 1   V1      284807 non-null  float64
 2   V2      284807 non-null  float64
 3   V3      284807 non-null  float64
 4   V4      284807 non-null  float64
 5   V5      284807 non-null  float64
 6   V6      284807 non-null  float64
 7   V7      284807 non-null  float64
 8   V8      284807 non-null  float64
 9   V9      284807 non-null  float64
 10  V10     284807 non-null  float64
 11  V11     284807 non-null  float64
 12  V12     284807 non-null  float64
 13  V13     284807 non-null  float64
 14  V14     284807 non-null  float64
 15  V15     284807 non-null  float64
 16  V16     284807 non-null  float64
 17  V17     284807 non-null  float64
 18  V18     284807 non-null  float64
 19  V19     284807 non-null  float64
 20  V20     284807 non-null  float64
 21  V21     284807 non-null  float64
 22  V22     284807 non-null  float64
 23  V23     284807 non-null  float64
 24  V24     284807 non-null  float64
 25  V25     284807 non-null  float64
 26  V26     284807 non-null  float64
 27  V27     284807 non-null  float64
 28  V28     284807 non-null  float64
 29  Amount  284807 non-null  float64
 30  Class   284807 non-null  int64
dtypes: float64(30), int64(1)
memory usage: 67.4 MB

In [7]:
df.isnull().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       0
V16       0
V17       0
V18       0
V19       0
V20       0
V21       0
V22       0
V23       0
V24       0
V25       0
V26       0
V27       0
V28       0
Amount    0
Class     0
dtype: int64

# Distribution of legit transactions & Fraudulant transaction

In [8]:
df['Class'].value_counts()

0    284315
1       492
Name: Class, dtype: int64

# This dataset is highly unbalanced
0--> Normal Transaction
1--> Fraudulant Transaction

In [12]:
Legit= df[df.Class==0]
Fraud= df[df.Class==1]

In [18]:
print(Legit.shape)
print(Fraud.shape)

(284315, 31)
(492, 31)

In [20]:
Legit.Amount.describe()

count    284315.000000
mean         88.291022
std         250.105092
min           0.000000
25%           5.650000
50%          22.000000
75%          77.050000
max       25691.160000
Name: Amount, dtype: float64

In [21]:
Fraud.Amount.describe()

count     492.000000
mean      122.211321
std       256.683288
min         0.000000
25%         1.000000
50%         9.250000
75%       105.890000
max      2125.870000
Name: Amount, dtype: float64

# Comparing the values for both transactions

In [22]:
df.groupby('Class').mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0,94838.202258,0.008258,-0.006271,0.012171,-0.007860,0.005453,0.002419,0.009637,-0.000987,0.004467,...,-0.000644,-0.001235,-0.000024,0.000070,0.000182,-0.000072,-0.000089,-0.000295,-0.000131,88.291022
1,80746.806911,-4.771948,3.623778,-7.033281,4.542029,-3.151225,-1.397737,-5.568731,0.570636,-2.581123,...,0.372319,0.713588,0.014049,-0.040308,-0.105130,0.041449,0.051648,0.170575,0.075667,122.211321

# Undersampling

Build a sample dataset containing similar distribution of normal transaction and fraudulant Transaction

fraud Dataset--> 492

In [23]:
legit_sample = Legit.sample(n=492)

In [24]:
new_df = pd.concat([legit_sample,Fraud],axis=0)

In [25]:
new_df

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
187329,127483.0,1.967284,-0.478105,-0.431467,-0.045342,-0.524841,-0.029725,-0.728513,0.220441,1.196901,...,-0.154708,-0.396808,0.438570,0.651208,-0.561369,-0.330400,-0.001212,-0.042451,0.92,0
263509,160987.0,-0.800300,0.989212,-1.507041,-1.978554,0.148091,-1.965259,0.796206,0.169743,-2.116046,...,0.687687,1.664631,-0.446580,0.144010,0.422898,0.154616,-0.296590,-0.002353,20.00,0
179191,123962.0,2.124485,-0.107674,-1.509747,0.178449,0.342655,-0.620870,0.159012,-0.260699,0.636639,...,-0.356052,-0.906764,0.208692,-1.007817,-0.167217,0.260335,-0.074221,-0.069843,7.44,0
28913,35231.0,0.678800,-0.841755,0.585873,1.357550,-0.568447,0.787592,-0.275203,0.163752,0.667850,...,0.259715,0.394195,-0.398369,-0.724015,0.465111,-0.189868,0.037094,0.070403,266.42,0
114038,73307.0,-0.777846,0.739113,2.633886,0.575467,0.207245,0.283643,0.860626,-0.402662,0.032796,...,-0.189435,-0.231439,-0.137755,0.138591,-0.168429,-0.602441,-0.768468,-0.626041,11.98,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
279863,169142.0,-1.927883,1.125653,-4.518331,1.749293,-1.566487,-2.010494,-0.882850,0.697211,-2.064945,...,0.778584,-0.319189,0.639419,-0.294885,0.537503,0.788395,0.292680,0.147968,390.00,1
280143,169347.0,1.378559,1.289381,-5.004247,1.411850,0.442581,-1.326536,-1.413170,0.248525,-1.127396,...,0.370612,0.028234,-0.145640,-0.081049,0.521875,0.739467,0.389152,0.186637,0.76,1
280149,169351.0,-0.676143,1.126366,-2.213700,0.468308,-1.120541,-0.003346,-2.234739,1.210158,-0.652250,...,0.751826,0.834108,0.190944,0.032070,-0.739695,0.471111,0.385107,0.194361,77.89,1
281144,169966.0,-3.113832,0.585864,-5.399730,1.817092,-0.840618,-2.943548,-2.208002,1.058733,-1.632333,...,0.583276,-0.269209,-0.456108,-0.183659,-0.328168,0.606116,0.884876,-0.253700,245.00,1
281674,170348.0,1.991976,0.158476,-2.583441,0.408670,1.151147,-0.096695,0.223050,-0.068384,0.577829,...,-0.164350,-0.295135,-0.072173,-0.450261,0.313267,-0.289617,0.002988,-0.015309,42.53,1

In [26]:
new_df['Class'].value_counts()

0    492
1    492
Name: Class, dtype: int64

In [27]:
new_df.groupby('Class').mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0,94574.329268,0.027591,0.023502,0.023328,0.023080,-0.012772,0.086927,0.022432,0.081467,-0.019618,...,-0.004773,-0.042634,-0.052473,-0.000126,-0.028335,-0.009597,-0.003244,-0.009820,-0.017396,86.675691
1,80746.806911,-4.771948,3.623778,-7.033281,4.542029,-3.151225,-1.397737,-5.568731,0.570636,-2.581123,...,0.372319,0.713588,0.014049,-0.040308,-0.105130,0.041449,0.051648,0.170575,0.075667,122.211321

# Splitting the data into Features and Targets

In [28]:
x=new_df.drop(columns='Class',axis=1)
y=new_df['Class']

In [29]:
y

187329    0
263509    0
179191    0
28913     0
114038    0
         ..
279863    1
280143    1
280149    1
281144    1
281674    1
Name: Class, Length: 984, dtype: int64

In [31]:
x

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
187329,127483.0,1.967284,-0.478105,-0.431467,-0.045342,-0.524841,-0.029725,-0.728513,0.220441,1.196901,...,-0.249449,-0.154708,-0.396808,0.438570,0.651208,-0.561369,-0.330400,-0.001212,-0.042451,0.92
263509,160987.0,-0.800300,0.989212,-1.507041,-1.978554,0.148091,-1.965259,0.796206,0.169743,-2.116046,...,-0.286282,0.687687,1.664631,-0.446580,0.144010,0.422898,0.154616,-0.296590,-0.002353,20.00
179191,123962.0,2.124485,-0.107674,-1.509747,0.178449,0.342655,-0.620870,0.159012,-0.260699,0.636639,...,-0.189612,-0.356052,-0.906764,0.208692,-1.007817,-0.167217,0.260335,-0.074221,-0.069843,7.44
28913,35231.0,0.678800,-0.841755,0.585873,1.357550,-0.568447,0.787592,-0.275203,0.163752,0.667850,...,0.422510,0.259715,0.394195,-0.398369,-0.724015,0.465111,-0.189868,0.037094,0.070403,266.42
114038,73307.0,-0.777846,0.739113,2.633886,0.575467,0.207245,0.283643,0.860626,-0.402662,0.032796,...,0.005331,-0.189435,-0.231439,-0.137755,0.138591,-0.168429,-0.602441,-0.768468,-0.626041,11.98
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
279863,169142.0,-1.927883,1.125653,-4.518331,1.749293,-1.566487,-2.010494,-0.882850,0.697211,-2.064945,...,1.252967,0.778584,-0.319189,0.639419,-0.294885,0.537503,0.788395,0.292680,0.147968,390.00
280143,169347.0,1.378559,1.289381,-5.004247,1.411850,0.442581,-1.326536,-1.413170,0.248525,-1.127396,...,0.226138,0.370612,0.028234,-0.145640,-0.081049,0.521875,0.739467,0.389152,0.186637,0.76
280149,169351.0,-0.676143,1.126366,-2.213700,0.468308,-1.120541,-0.003346,-2.234739,1.210158,-0.652250,...,0.247968,0.751826,0.834108,0.190944,0.032070,-0.739695,0.471111,0.385107,0.194361,77.89
281144,169966.0,-3.113832,0.585864,-5.399730,1.817092,-0.840618,-2.943548,-2.208002,1.058733,-1.632333,...,0.306271,0.583276,-0.269209,-0.456108,-0.183659,-0.328168,0.606116,0.884876,-0.253700,245.00
281674,170348.0,1.991976,0.158476,-2.583441,0.408670,1.151147,-0.096695,0.223050,-0.068384,0.577829,...,-0.017652,-0.164350,-0.295135,-0.072173,-0.450261,0.313267,-0.289617,0.002988,-0.015309,42.53

# Splitting the data into Train and Test

In [33]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,stratify=y,random_state=2)

In [36]:
print(x_train.shape)

(787, 30)

# Model Selection & Fitting

In [37]:
model = LogisticRegression()

In [38]:
model.fit(x_train,y_train)

C:\Users\DataScience\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

# Model Evaluvation

In [40]:
x_train_prediction = model.predict(x_train)
training_data_accuracy = accuracy_score(x_train_prediction, y_train)

In [41]:
print("Accuracy on Training Data :", training_data_accuracy)

Accuracy on Training Data : 0.9491740787801779

In [43]:
x_test_prediction = model.predict(x_test)
test_data_accuracy = accuracy_score(x_test_prediction, y_test)

In [44]:
print("Accuracy on Testing Data :", test_data_accuracy)

Accuracy on Testing Data : 0.8934010152284264

In [45]:
model.score(x_test,y_test)

0.8934010152284264

In [46]:
model.score(x_train,y_train)

0.9491740787801779